services:
  postgres:
    image: postgres:latest
    volumes:
      - ../postgres/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      SCHEMA: public
  app:
    image: app/app:1.0
    ports:
      - 8080:8080
  client:
    image: client/client:1.0
    ports:
      - 3000:3000

networks:
  app-network: